-- =====================================================
-- CARGA COMPLETA DE INVENTARIO - 2026-02-05T01:45:23.578Z
-- =====================================================

BEGIN;

-- CATEGORIAS
INSERT INTO categories (platform_id, platform_name) VALUES (1, 'pulseras y medallas rojas caja ');
INSERT INTO categories (platform_id, platform_name) VALUES (2, 'pulseras de cristales caja c');
INSERT INTO categories (platform_id, platform_name) VALUES (3, 'pulseras hilos con cristales ca');
INSERT INTO categories (platform_id, platform_name) VALUES (4, 'pulseras parejas caja e');
INSERT INTO categories (platform_id, platform_name) VALUES (5, 'pulseras de cobre y acerocon pi');
INSERT INTO categories (platform_id, platform_name) VALUES (6, 'pulsera de piedras caja g');
INSERT INTO categories (platform_id, platform_name) VALUES (7, 'acero con nudo de brujas caja h');
INSERT INTO categories (platform_id, platform_name) VALUES (8, 'acero caja i');
INSERT INTO categories (platform_id, platform_name) VALUES (9, 'pulseras de cuero caja j');
INSERT INTO categories (platform_id, platform_name) VALUES (10, 'charm');
INSERT INTO categories (platform_id, platform_name) VALUES (11, 'aros');
INSERT INTO categories (platform_id, platform_name) VALUES (12, 'anillos');
INSERT INTO categories (platform_id, platform_name) VALUES (13, 'pulseras');
INSERT INTO categories (platform_id, platform_name) VALUES (14, 'cadenas hombre');
INSERT INTO categories (platform_id, platform_name) VALUES (15, 'rosarios');
INSERT INTO categories (platform_id, platform_name) VALUES (16, 'dijes');

-- PRODUCTOS
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00002/169', 'HR00002/169', 48, 3591, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00003/163', 'HR00003/163', 87, 3591, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00010', 'HR00010', 89, 3591, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00011', 'HR00011', 50, 2966, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00014', 'HR00014', 196, 5091, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00015', 'HR00015', 33, 3901, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00016', 'HR00016', 79, 3391, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00017', 'HR00017', 27, 4851, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00018', 'HR00018', 18, 2691, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00019', 'HR00019', 39, 3592, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00020', 'HR00020', 1, 3304, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00021', 'HR00021', 14, 3992, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00022', 'HR00022', 39, 4265, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00023', 'HR00023', 46, 4265, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00024', 'HR00024', 16, 4740, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00025', 'HR00025', 25, 4740, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00026', 'HR00026', 126, 4265, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR0027', 'HR0027', 20, 0, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR0028', 'HR0028', 100, 0, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HRI0002', 'HRI0002', 66, 4266, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HRI0004', 'HRI0004', 13, 4041, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HRI0005', 'HRI0005', 11, 0, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HRI0006', 'HRI0006', 50, 0, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCR0002', 'PCR0002', 5, 3390, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCR0004', 'PCR0004', 9, 3912, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCR0006', 'PCR0006', 4, 4491, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCR0010', 'PCR0010', 161, 3771, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCR0012 /PC0012', 'PCR0012 /PC0012', 43, 4792, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCR0013', 'PCR0013', 31, 7992, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('MCR0001 /133', 'MCR0001 /133', 1, 3141, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('MCR0002', 'MCR0002', 0, 3391, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('MCR0003', 'MCR0003', 65, 3141, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('MCR0004', 'MCR0004', 39, 2286, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('MCR0005', 'MCR0005', 89, 2669, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('MCR0006', 'MCR0006', 42, 2792, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PRENPLATA02', 'PRENPLATA02', 3, 5140, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PRENPLATA03', 'PRENPLATA03', 56, 8091, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PRENPLATA04', 'PRENPLATA04', 15, 6877, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PRENPLATA05', 'PRENPLATA05', 0, 5347, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PRENPLATA06', 'PRENPLATA06', 26, 7912, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HN0003', 'HN0003', 34, 2556, 1);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCR0007', 'PCR0007', 362, 450, 2);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCR0008', 'PCR0008', 182, 500, 2);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCR0009', 'PCR0009', 140, 550, 2);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HRACERO01', 'HRACERO01', 9, 1000, 2);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HRACERO03', 'HRACERO03', 11, 583, 2);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HRACERO04', 'HRACERO04', 4, 583, 2);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HRACERO08', 'HRACERO08', 204, 500, 2);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HRACERO09', 'HRACERO09', 295, 500, 2);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCACERO01', 'PCACERO01', 133, 1000, 2);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCACERO02', 'PCACERO02', 11, 1000, 2);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCACERO03', 'PCACERO03', 13, 1000, 2);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCACERO04', 'PCACERO04', 4, 1000, 2);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO35', 'ACERO35', 24, 1500, 2);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('MEDALLAACERO01', 'MEDALLAACERO01', 54, 1000, 3);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HRACERO05A', 'HRACERO05A', 1, 1000, 3);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HRACERO06', 'HRACERO06', 74, 500, 3);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HRACERO010', 'HRACERO010', 38, 450, 3);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00013', 'HR00013', 104, 450, 3);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00013B', 'HR00013B', 53, 459, 3);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCACERO05', 'PCACERO05', 45, 834, 3);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO16', 'ACERO16', 0, 1000, 3);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO16B', 'ACERO16B', 0, 1000, 3);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PBEBE01', 'PBEBE01', 29, 1000, 3);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00008', 'HR00008', 106, 300, 3);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00009', 'HR00009', 537, 300, 3);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HR00009 /155', 'HR00009 /155', 0, 0, 3);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('HNEGRO01', 'HNEGRO01', 120, 400, 3);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP01', 'PP01', 0, 1500, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP02', 'PP02', 3, 1500, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP03', 'PP03', 3, 1500, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP04', 'PP04', 5, 1500, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP05', 'PP05', 4, 1500, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP06', 'PP06', 6, 1500, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP07', 'PP07', 135, 1500, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP08', 'PP08', 91, 1500, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP09', 'PP09', 96, 1500, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP10', 'PP10', 148, 1500, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP11', 'PP11', 95, 1500, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP12', 'PP12', 413, 1000, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPAREJA03', 'PPAREJA03', 6, 1250, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP13', 'PP13', 20, 834, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP14', 'PP14', 20, 834, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PP15', 'PP15', 20, 1000, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('LLAVERO01', 'LLAVERO01', 6, 2560, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO01', 'ACERO01', 8, 1700, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO03', 'ACERO03', 10, 1700, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO04', 'ACERO04', 5, 1700, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO05', 'ACERO05', 2, 1700, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO06', 'ACERO06', 1, 1700, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO07', 'ACERO07', 3, 1700, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO08', 'ACERO08', 2, 1700, 4);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCOBRE01', 'PCOBRE01', 15, 800, 5);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCOBRE02', 'PCOBRE02', 217, 800, 5);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCOBRE03', 'PCOBRE03', 237, 800, 5);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCOBRE04', 'PCOBRE04', 50, 800, 5);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO09', 'ACERO09', 79, 800, 5);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO28', 'ACERO28', 67, 1300, 5);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO38', 'ACERO38', 89, 1300, 5);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ANIACERO01', 'ANIACERO01', 34, 800, 5);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('COACERO02', 'COACERO02', 26, 1000, 5);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('COACERO03', 'COACERO03', 6, 1800, 5);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('COCUERO01', 'COCUERO01', 29, 700, 5);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PDIJE01', 'PDIJE01', 1, 6000, 5);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PDIJE02', 'PDIJE02', 1, 3000, 5);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPIEDRA01', 'PPIEDRA01', 91, 2000, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPIEDRA03', 'PPIEDRA03', 76, 2000, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPIEDRA04', 'PPIEDRA04', 19, 4500, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPIEDRA05', 'PPIEDRA05', 19, 3000, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO25', 'ACERO25', 11, 2900, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO29', 'ACERO29', 20, 2000, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('YAPAMALA01', 'YAPAMALA01', 4, 2000, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('YAPAMALA02', 'YAPAMALA02', 15, 3000, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('OGOLD01 /142', 'OGOLD01 /142', 4, 5712, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('OGOLD02/ 120', 'OGOLD02/ 120', 2, 10472, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('OGOLD05 / 143', 'OGOLD05 / 143', 3, 3332, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('VELA01', 'VELA01', 0, 2800, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('VELA02', 'VELA02', 0, 2800, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('VELA03', 'VELA03', 0, 2800, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('VELA04', 'VELA04', 0, 2800, 6);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO10', 'ACERO10', 60, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO10A', 'ACERO10A', 15, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO27', 'ACERO27', 9, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO23', 'ACERO23', 10, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO17', 'ACERO17', 29, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO21', 'ACERO21', 10, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO22', 'ACERO22', 10, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO24', 'ACERO24', 11, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO11', 'ACERO11', 29, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO13', 'ACERO13', 27, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO14', 'ACERO14', 4, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO12', 'ACERO12', 33, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO19', 'ACERO19', 16, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO18', 'ACERO18', 19, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO34', 'ACERO34', 7, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO20', 'ACERO20', 34, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO11R', 'ACERO11R', 4, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO34O', 'ACERO34O', 20, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO26', 'ACERO26', 14, 2900, 7);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CACERO01', 'CACERO01', 0, 7140, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CACERO02', 'CACERO02', 0, 7140, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CACERO03', 'CACERO03', 0, 700, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CACERO04A', 'CACERO04A', 8, 2142, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CACERO04B', 'CACERO04B', 14, 1785, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CACERO05', 'CACERO05', 0, 0, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO06A', 'ACERO06A', 18, 2975, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CACERO07', 'CACERO07', 49, 2975, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CACERO08', 'CACERO08', 72, 2975, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CACERO09', 'CACERO09', 11, 2142, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CACERO10', 'CACERO10', 7, 3570, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CACERO11', 'CACERO11', 13, 3570, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO36', 'ACERO36', 13, 1428, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO37A', 'ACERO37A', 7, 4165, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO37B', 'ACERO37B', 1, 4165, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACERO39', 'ACERO39', 11, 2380, 8);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PC02', 'PC02', 29, 1000, 9);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PC04', 'PC04', 44, 1000, 9);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PC05', 'PC05', 6, 1000, 9);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PC06', 'PC06', 34, 1000, 9);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PC07', 'PC07', 10, 1000, 9);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPERL004', 'PPERL004', 10, 2000, 9);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('DIJPLATA15', 'DIJPLATA15', 2, 5535, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('DIJPLATA40', 'DIJPLATA40', 1, 4480, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA02', 'CHARMPLA02', 17, 4790, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA04', 'CHARMPLA04', 21, 4591, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA05', 'CHARMPLA05', 26, 8353, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA06', 'CHARMPLA06', 36, 6451, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA07', 'CHARMPLA07', 11, 7591, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA08', 'CHARMPLA08', 12, 5691, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA09', 'CHARMPLA09', 12, 6640, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA10', 'CHARMPLA10', 4, 5691, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA11', 'CHARMPLA11', 18, 7116, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA12', 'CHARMPLA12', 7, 7515, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA13', 'CHARMPLA13', 6, 7515, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA14', 'CHARMPLA14', 26, 7591, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA15', 'CHARMPLA15', 25, 6641, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA16', 'CHARMPLA16', 19, 8541, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA17', 'CHARMPLA17', 10, 4741, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA18', 'CHARMPLA18', 15, 5691, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA19', 'CHARMPLA19', 61, 7192, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA20', 'CHARMPLA20', 26, 6641, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA21', 'CHARMPLA21', 94, 5592, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHARMPLA22', 'CHARMPLA22', 38, 7473, 10);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATOPE01', 'ATOPE01', 5, 2450, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATOPE02', 'ATOPE02', 13, 2850, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATOPE03', 'ATOPE03', 5, 2450, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATOPE04', 'ATOPE04', 5, 1950, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATOPE05', 'ATOPE05', 3, 1950, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATOPE06', 'ATOPE06', 48, 1950, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATOPE07', 'ATOPE07', 4, 2450, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATOPE08', 'ATOPE08', 4, 2450, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATOPE09', 'ATOPE09', 13, 2450, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATOPE11', 'ATOPE11', 13, 2450, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATOPE13', 'ATOPE13', 8, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATOPE14', 'ATOPE14', 7, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATOPE15', 'ATOPE15', 10, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATOPE16', 'ATOPE16', 5, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA01', 'APLATA01', 35, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA02', 'APLATA02', 4, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA03 / 168', 'APLATA03 / 168', 14, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA07', 'APLATA07', 0, 5938, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA08', 'APLATA08', 4, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA10', 'APLATA10', 3, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA11', 'APLATA11', 7, 4990, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA12', 'APLATA12', 9, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA13', 'APLATA13', 30, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA15', 'APLATA15', 69, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA18', 'APLATA18', 49, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA19', 'APLATA19', 10, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA20', 'APLATA20', 39, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA21', 'APLATA21', 9, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA22', 'APLATA22', 7, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA23', 'APLATA23', 5, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA26', 'APLATA26', 90, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA27', 'APLATA27', 70, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA28', 'APLATA28', 62, 3791, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA29', 'APLATA29', 34, 2651, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA30', 'APLATA30', 15, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA31', 'APLATA31', 17, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA32', 'APLATA32', 24, 12590, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA33', 'APLATA33', 36, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA34', 'APLATA34', 15, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA35', 'APLATA35', 25, 5820, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA36', 'APLATA36', 10, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA37', 'APLATA37', 15, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA38', 'APLATA38', 27, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA39', 'APLATA39', 23, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA40', 'APLATA40', 12, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA41', 'APLATA41', 15, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA42', 'APLATA42', 20, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA43', 'APLATA43', 4, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA44', 'APLATA44', 20, 1900, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA45', 'APLATA45', 15, 6300, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APLATA46', 'APLATA46', 17, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL01', 'ACRISTAL01', 7, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL02', 'ACRISTAL02', 10, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL06', 'ACRISTAL06', 1, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL07', 'ACRISTAL07', 3, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL08', 'ACRISTAL08', 9, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL10', 'ACRISTAL10', 9, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL12', 'ACRISTAL12', 6, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL13', 'ACRISTAL13', 7, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL15', 'ACRISTAL15', 19, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL16', 'ACRISTAL16', 15, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL17', 'ACRISTAL17', 36, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL18', 'ACRISTAL18', 5, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL19', 'ACRISTAL19', 30, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL20', 'ACRISTAL20', 30, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACRISTAL21', 'ACRISTAL21', 0, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACIRCON601', 'ACIRCON601', 2, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACIRCON602', 'ACIRCON602', 1, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACIRCON603', 'ACIRCON603', 2, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACIRCON604', 'ACIRCON604', 4, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACIRCON605', 'ACIRCON605', 3, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACIRCON606', 'ACIRCON606', 5, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACIRCON802', 'ACIRCON802', 2, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACIRCON803', 'ACIRCON803', 1, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACIRCON805', 'ACIRCON805', 4, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACIRCON806', 'ACIRCON806', 86, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ACIRCON607', 'ACIRCON607', 40, 2392, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AORO01', 'AORO01', 12, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AORO02', 'AORO02', 3, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AORO03', 'AORO03', 20, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('APIERCING01', 'APIERCING01', 1, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ABRONCE01', 'ABRONCE01', 3, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ABRONCE02', 'ABRONCE02', 1, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ATRIO01', 'ATRIO01', 5, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA01', 'AARGOLLA01', 2, 5790, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA03', 'AARGOLLA03', 24, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA04', 'AARGOLLA04', 1, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA06', 'AARGOLLA06', 5, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA07', 'AARGOLLA07', 19, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA08', 'AARGOLLA08', 12, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA09', 'AARGOLLA09', 20, 9590, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA10', 'AARGOLLA10', 11, 9990, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA11', 'AARGOLLA11', 34, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA12', 'AARGOLLA12', 35, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA13', 'AARGOLLA13', 13, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA14', 'AARGOLLA14', 28, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA15', 'AARGOLLA15', 13, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA16', 'AARGOLLA16', 8, 10725, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA17', 'AARGOLLA17', 30, 8675, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA18', 'AARGOLLA18', 20, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AARGOLLA19', 'AARGOLLA19', 65, 0, 11);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ANIPLATA01', 'ANIPLATA01', 4, 0, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ANIPLATA02', 'ANIPLATA02', 3, 0, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ANIPLATA05', 'ANIPLATA05', 15, 0, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ANIPLATA06', 'ANIPLATA06', 5, 0, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ANIPLATA07', 'ANIPLATA07', 5, 0, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ANIPLATA08', 'ANIPLATA08', 5, 0, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ANIPLATA09', 'ANIPLATA09', 1, 0, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ANIPLATA10', 'ANIPLATA10', 1, 0, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ANIPLATA11', 'ANIPLATA11', 95, 0, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ANIORO01', 'ANIORO01', 3, 0, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ANIORO02', 'ANIORO02', 2, 0, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ANIORO03', 'ANIORO03', 2, 0, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AMIDI01', 'AMIDI01', 22, 1750, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AMIDI02', 'AMIDI02', 10, 1750, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('AMIDI03', 'AMIDI03', 10, 1750, 12);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPLATA002', 'PPLATA002', 14, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPLATA003 /172', 'PPLATA003 /172', 29, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPLATA004 /170', 'PPLATA004 /170', 3, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPLATA005', 'PPLATA005', 3, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPLATA006', 'PPLATA006', 35, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPLATA011', 'PPLATA011', 11, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPLATA012', 'PPLATA012', 54, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPLATA013', 'PPLATA013', 14, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPLATA014', 'PPLATA014', 7, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPLATA016', 'PPLATA016', 109, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPLATA017', 'PPLATA017', 18, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPLATA019', 'PPLATA019', 41, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPLATA020', 'PPLATA020', 46, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPLATA021', 'PPLATA021', 25, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PSB02', 'PSB02', 19, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PSB03', 'PSB03', 24, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCRUZSB01', 'PCRUZSB01', 10, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCRUZSB02', 'PCRUZSB02', 37, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCRUZ0001', 'PCRUZ0001', 6, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PTENIS0002', 'PTENIS0002', 13, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PTENIS0003', 'PTENIS0003', 10, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PTENIS0004', 'PTENIS0004', 10, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PTENIS0005', 'PTENIS0005', 15, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PINF0001', 'PINF0001', 8, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PINF0002', 'PINF0002', 5, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('POROINF0001', 'POROINF0001', 10, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PORO00001', 'PORO00001', 2, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('TORO001', 'TORO001', 2, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCRIST0001', 'PCRIST0001', 34, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCRIST0002', 'PCRIST0002', 33, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PCRIST0003', 'PCRIST0003', 5, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PHOMBRE05', 'PHOMBRE05', 7, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PHOMBRE06', 'PHOMBRE06', 4, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PHOMBRE07', 'PHOMBRE07', 1, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PHOMBRE08', 'PHOMBRE08', 1, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PHOMBRE09', 'PHOMBRE09', 1, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PHOMBRE10', 'PHOMBRE10', 5, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PHOMBRE12', 'PHOMBRE12', 12, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PHOMBRE13', 'PHOMBRE13', 21, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ESCLAVAPLA02', 'ESCLAVAPLA02', 8, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ESCLAVAPLA03', 'ESCLAVAPLA03', 24, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPERL0003', 'PPERL0003', 17, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPERL0006', 'PPERL0006', 6, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPERL0007', 'PPERL0007', 14, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('PPERL0008', 'PPERL0008', 30, 0, 13);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHOMBRE01', 'CHOMBRE01', 8, 0, 14);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHOMBRE02', 'CHOMBRE02', 10, 0, 14);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHOMBRE03', 'CHOMBRE03', 10, 0, 14);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHOMBRE04', 'CHOMBRE04', 1, 0, 14);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHOMBRE05', 'CHOMBRE05', 10, 0, 14);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHOMBRE07', 'CHOMBRE07', 32, 0, 14);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHOMBRE08', 'CHOMBRE08', 21, 0, 14);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHOMBRE12', 'CHOMBRE12', 12, 0, 14);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHOMBRE13', 'CHOMBRE13', 5, 0, 14);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHOMBRE14', 'CHOMBRE14', 10, 0, 14);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHOMBRE15', 'CHOMBRE15', 5, 0, 14);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHOMBRE16', 'CHOMBRE16', 15, 0, 14);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('CHOMBRE17', 'CHOMBRE17', 5, 0, 14);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ROSARIO01', 'ROSARIO01', 14, 0, 15);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ROSARIO02', 'ROSARIO02', 7, 0, 15);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ROSARIO04', 'ROSARIO04', 14, 0, 15);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ROSARIO05', 'ROSARIO05', 10, 0, 15);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('ROSARIO06', 'ROSARIO06', 7, 0, 15);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('DIJPLATA01/ 140 1401', 'DIJPLATA01/ 140 1401', 43, 0, 16);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('DIJPLATA03', 'DIJPLATA03', 27, 0, 16);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('DIJPLATA04', 'DIJPLATA04', 34, 0, 16);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('DIJPLATA05 AYB / 152 153', 'DIJPLATA05 AYB / 152 153', 14, 0, 16);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('DIJPLATA06', 'DIJPLATA06', 19, 0, 16);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('DIJPLATA07', 'DIJPLATA07', 0, 0, 16);
INSERT INTO products (internal_sku, name, stock, cost, "categoryPlatformId") VALUES ('DIJPLATA08', 'DIJPLATA08', 0, 0, 16);

COMMIT;

-- Total categorias: 16
-- Total productos: 369
